site_name: Radia Perlman | AgroMart
docs_dir: docs
nav:
  - Home: index.md
  - Sobre o AgroMart: pages/01-agromart/sobre.md
  - Propósito e Processo de Avaliação de Produto: pages/02-processo/processo-avaliacao.md
  - Especificação da Avaliação pelo GQM:
      - Definição: pages/03-gqm/definicao.md
      - Detalhamento: pages/03-gqm/abstraction.md
  - Projeção da Avaliação e Cronograma: pages/04-cron/cronograma.md
  - Q-Rapids: pages/05-qrapids/qrapids.md
  - Resultados Obtidos:
      - Usabilidade: pages/06-resultados/usabilidade.md
      - Eficiência: pages/06-resultados/eficiencia.md
  - Dashboard PSM/CID Equipe: pages/07-dashboard/dashboard.md
  - Tutorial para Rodar o Agromart Local: pages/08-agromart-local/agromart-local.md
  - Materiais de Apresentações: pages/09-apresentacoes/apresentacoes.md
extra_css:
  - assets/custom.css
theme:
  name: material

  palette:
    - scheme: default
      primary: 'custom'
      accent: 'lime'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mude para o tema escuro
        
    - scheme: slate
      primary: 'custom'
      accent: 'lime'
      toggle:
        icon: material/toggle-switch
        name: Mude para o tema claro
  
  logo: assets/UnB_Logo.png
  favicon: assets/UnB_Logo.png
  highlightjs: true

markdown_extensions:
  - toc:
      permalink: true