site_name: Radia Perlman
nav:
  - Home: index.md
  - Agromart: sobre.md
  - Processo Avaliação: processo-avaliacao.md
  - Abstraction Sheet: abstraction-sheet.md
extra_css:
  - assets/custom.css
theme:
  name: material
markdown_extensions:
  - toc:
      permalink: true